keys:
  - &user_joebutler age1egqnsgczkpametatgdl4fua3ea49p5dmt22kwhslykccujjn2qls3q5el4
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_joebutler
