keys:
  - &user_joebutler age1hrpwus9sx4emw5hamej3phajpclmpt3yqvwdscfsg6qyqlp2rcssllcnlr
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_joebutler
