{
  imports = [
    ./anki-forge.nix
    ./foot.nix
    ./hyprland.nix
    ./hyprland-extras.nix
    ./mako.nix
    ./opencode.nix
    ./rofi.nix
    ./starship.nix
    ./thunar.nix
    ./waybar.nix
    ./wlogout/wlogout.nix
    ./whichkey.nix
    ./yazi.nix
    ./zathura.nix
    ./zsh.nix
  ];
}
