{ pkgs, lib, config, ... }: {
  programs.opencode = {
    enable = true;
    settings = {
      # The MCP configuration will be generated by the MCP service
      # and read from the generated JSON file
      mcp = builtins.fromJSON (builtins.readFile "${config.xdg.configHome}/opencode/mcp.json");
    };
  };
}
