{config, ...}: {
  programs.opencode = {
    enable = true;
    settings = {
      # The MCP configuration is generated by the MCP service
      inherit (config.services.mcp.openCodeConfig) mcp;
    };
  };
}
